<?php
namespace KmBundle\Command;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Question\ConfirmationQuestion;


class InitCacheCommand extends Command
{
    protected function configure() {
        //set the name of the command
        $this->setName('beezymanager:init:cache');
        //set the description when type bin/console
        $this->setDescription('Initialize the client cache');
        //set the helper message
        $this->setHelp(' (miniserver for a branch) cache at 100%');
        //Add the BranchId (synchroneId) argument
        //$this->addArgument('branchId', InputArgument::REQUIRED, 'The Branch #ID generated by the Server');
        $this->addArgument('branchId', InputArgument::REQUIRED, 'The Branch #ID');
    }
    
    protected function execute(InputInterface $input, OutputInterface $output) 
    {
        // outputs multiple lines to the console (adding "\n" at the end of each line)
        $output->writeln([
            'BeezyManager: Client Cache Initialization',
            '==========================================',
            '',
        ]);
        
        
        // outputs a message followed by a "\n"
        $output->writeln('Notice: Initialization succeed only when the STransactions are 
            fully synchronized or when setting up new Branch');

        
        $output->writeln('Branch #ID: '.$input->getArgument('branchId'));
        $output->writeln('Initializing...');
        
    }
    
}