user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

km:
    resource: "@KmBundle/Resources/config/routing.yml"
    prefix:   /

transaction:
    resource: "@TransactionBundle/Resources/config/routing.yml"
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
transactions:
    type: rest
    resource: TransactionBundle:Api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"