km_synchronizer:
    path:  /synchronizer
    defaults: { _controller: KmBundle:Default:synchronizer }
    
km_front:
    path:    /
    defaults: { _controller: KmBundle:Default:front }
    
sales: 
  type: rest
  resource:     "TransactionBundle:Api"
  prefix:  api