services:
    km.synchronizer_handler:
            class: KmBundle\Service\SynchronizerHandler
            arguments: ["@guzzle.client.api_crm", "@doctrine.orm.entity_manager", "%serverhost%"]

    km.admin.branch:
        class: KmBundle\Admin\BranchAdmin
        arguments: [~, KmBundle\Entity\Branch, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Branch }
